name: Deploy Storybook to GitHub pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Build Storybook and Deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2
      - name: Log environments
        run: |
          echo "Starting Storybook build"

      - name: npm install, build and test
        uses: actions/setup-node@v1
        with:
          node-version: "14.1.x"
      - run: npm ci
      - run: npm run storybook:build
        env:
          CI: true

      - id: publish
        name: Publish to NPM if version has been updated
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: ${{ steps.publish.outputs.version }}
          dry-run: true

      - name: Configure AWS credentials for CDN account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy landing page
        run: sh ./scripts/storybook-deploy.sh
        env:
          VERSION: ${{ steps.publish.outputs.version }}
          AWS_CLOUDFRONT_LANDINGPAGE_DIST_ID: ${{ secrets.AWS_CLOUDFRONT_LANDINGPAGE_DIST_ID }}
